stages:
  - build
  - deploy


cache:
#  key: '${CI_COMMIT_REF_SLUG}'
  key: 'cache-mensageiro'


build_job:
  stage: build
  image: docker:stable
  only:
    - tags

  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_job:
  stage: deploy
  image: registry.es.gov.br/espm/dockers/node:8.12.0-alpine
  only:
    - tags
  script:
    - npm i upgrade-rancher
    - ./node_modules/.bin/upgrade-rancher --IMAGE $CI_REGISTRY_IMAGE:$CI_BUILD_TAG --SERVICE_ID 1s768
    - ./node_modules/.bin/upgrade-rancher --IMAGE $CI_REGISTRY_IMAGE:$CI_BUILD_TAG --SERVICE_ID 1s788
  dependencies:
    - build_job
    